/* automatically generated by rust-bindgen 0.72.0 */

pub const WFB_QUERY:  i32 = 0;
pub const WFB_LOAD:   i32 = 1;
pub const WFB_STORE:  i32 = 2;
pub const WFB_RECALL: i32 = 3;
pub const WFB_HPREV:  i32 = 4;
pub const WFB_HNEXT:  i32 = 5;
pub type WubiForm = *mut c_void;
pub type WformButtonCb = std::option::Option<
	unsafe extern "C" fn(form: WubiForm, utf8p: *const c_char, utf8l: c_uint) -> c_int,
>;

unsafe extern "C" {
	pub fn wform_init_lib() -> WubiForm;
	pub fn wform_looping(form: WubiForm) -> c_int;
	pub fn wform_regiter_fun(form: WubiForm, which: c_int, fcb: WformButtonCb) -> c_int;
	pub fn wform_push_result(form: WubiForm, utf8p: *const c_char, utf8l: c_uint) -> c_int;
}
